//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_Portaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadastro
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public string AP { get; set; }
        public string BLOCO { get; set; }
        public string CARRO { get; set; }
        public string PLACA { get; set; }
    }
}
